### ISSUE TITLE
Why not use Int64 instead of float and go for millisecond precision where available?

### ISSUE THREAD

**Issue by georgkoester** [RealyUniqueName/DateTime#10]
I feel that removing the ms is a pity and for more general adaptation of the lib and language it would be very beneficial. That would be another clear selling point with respect to the default implementation.

**Comment by fullofcaffeine** [comment]
> As for milliseconds all use-cases for such features i know are measurements between two execution points in code, which is perfectly doable with haxe.Timer.stamp().
So i decided to not include milliseconds to simplify code even more.

That makes sense. Perhaps adding this to the README would make it clearer why milliseconds precision is not available.
