### ISSUE TITLE
Can not use datetime on Android

### ISSUE THREAD

**Issue by ocpear** [RealyUniqueName/DateTime#13]
I has installed datetime on haxe (haxelib install datetime) to get timezone offset. It run ok on Neko. But when I run on Android (lime test android), it runtime error. What's wrong?
Please help me. 
Thanks.

import datetime.DateTime;
import datetime.Timezone;
class DateHelper 
{
    public function getTimeZone():Void{
      trace(Timezone.local().getOffset(DateTime.local()));
    }
}

**Comment by RealyUniqueName** [comment]
What kind of error does it throw?

**Comment by ocpear** [comment]
I check as below. It only show 1 on the console and exit the app instantly when i run on Android (lime test android). 
If I run on Neko(lime test neko), it show 1 and 2 and not exit the app.
Please help me.
Thanks

import datetime.DateTime;
import datetime.Timezone;
class DateHelper 
{
public function getTimeZone():Void{
trace("1");
trace(Timezone.local().getOffset(DateTime.local()));
trace("2");
}
}

**Comment by RealyUniqueName** [comment]
Sorry, i still had no time to find the reason, but so far it looks like either `haxe.crypto.Base64`  does not work on adnroid or android can't handle large inlined strings in code.
