### ISSUE TITLE
bug when year change

### ISSUE THREAD

**Issue by bablukid** [RealyUniqueName/DateTime#17]
```
var d = DateTime.now();
Sys.println(d.getDate());
		
var a = d.snap(Month(Down)).add(Month(-6));
Sys.println(a.getDate());
```
outputs
```
2017-06-06 14:31:36
2017-12-01 01:00:00
```

Why the second date is not **2016**-12-01 01:00:00
Why the hour is not 00:00:00 ? ( because of day light saving ?? )

( I'm using haxe 3.2.1 with neko )

Another strange case

```
var d = DateTime.now();
Sys.println(d.getDate());
		
var a = d.snap(Month(Down)).add(Month(-2));
Sys.println(a.getDate());
```
outputs
```
2017-06-06 14:36:47
2017-04-01 02:00:00
```
Why the hour is not 00:00:00 ?

**Comment by RealyUniqueName** [comment]
Thanks for report!
I will upload new versions with this fix today.
As for hours, it's your timezone affects it, because `getDate()` returns a standard `Date` instance. If you want to print actual time saved in `DateTime` instance, use `d.toString()` or `d.format()`
