### ISSUE TITLE
Duplicate += operator for DTPeriod?

### ISSUE THREAD

**Issue by rcstuber** [RealyUniqueName/DateTime#23]
The `@:op(A += B)`exists twice for DTPeriod operations, instead a `@:op(A -= B)`operator is what we expect.

https://github.com/RealyUniqueName/DateTime/blob/0be6fbac466f5ba300de75a2818fd4ca41adf335/src/datetime/DateTime.hx#L683

**Comment by rcstuber** [comment]
Fast fix, thanks @RealyUniqueName !

**Comment by RealyUniqueName** [comment]
You're welcome )
